"""Validate the notes and regenerate their index.

This is the ripple mechanism. A change in the repository does not silently
invalidate a note: running this surfaces it. Four failures gate, each meaning
a note can no longer be trusted.

  a note covers a file that no longer exists
  a source file no note and no registry covers
  two decisions claim the same file
  a finding's evidence command no longer reproduces its claim

What counts as a source file is declared in notes/coverage.ini rather than
written here, because a scope hardcoded to one language and two directories is
how code quietly slips outside the check.

    python correctness/checks/check_notes.py             # structure and coverage
    python correctness/checks/check_notes.py --evidence  # also re-run findings
"""

from __future__ import annotations

import argparse
import configparser
import fnmatch
import importlib
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

KINDS = ('decision', 'finding', 'open', 'reference')
INDEX_HEADER = """# Notes index

Generated by `python correctness/checks/check_notes.py`. Do not edit.

Every note declares the files it covers; this table is built from those
declarations, so it cannot drift from the notes themselves.
"""


@dataclass
class Note:
    """One note: a decision, a finding, an open question, or a pointer."""

    path: Path
    kind: str
    title: str
    covers: list[str] = field(default_factory=list)
    claim: str = ''
    evidence: str = ''

    @property
    def slug(self) -> str:
        return self.path.stem


def parse(path: Path) -> Note:
    """Read one note's frontmatter.

    Raises
    ------
    ValueError
        When the note has no frontmatter, no title, or an unknown kind.
    """
    text = path.read_text(encoding='utf-8')
    if not text.startswith('---'):
        raise ValueError(f'{path}: no frontmatter')
    front = text.split('---', 2)[1]
    field_of = lambda name: (re.search(rf'^{name}:(.*)$', front, re.M) or [None, ''])[1].strip()
    kind, title = field_of('kind'), field_of('title')
    if kind not in KINDS:
        raise ValueError(f'{path}: kind must be one of {", ".join(KINDS)}, not {kind!r}')
    if not title:
        raise ValueError(f'{path}: no title')
    return Note(path=path, kind=kind, title=title,
                covers=[c.strip() for c in field_of('covers').split(',') if c.strip()],
                claim=field_of('claim'), evidence=field_of('evidence'))


def load_all(notes_root: Path) -> list[Note]:
    """Every note under notes_root, in path order; the index is not a note."""
    return [parse(p) for p in sorted(notes_root.rglob('*.md'))
            if p.name not in ('INDEX.md', 'README.md')]


def scope(notes_root: Path) -> configparser.SectionProxy:
    """The coverage scope declared in notes/coverage.ini."""
    parser = configparser.ConfigParser(allow_no_value=True)
    parser.read_string((notes_root / 'coverage.ini').read_text(encoding='utf-8'))
    return parser['coverage']


def _listed(section: configparser.SectionProxy, key: str) -> list[str]:
    return [part.strip() for part in (section.get(key) or '').split(',') if part.strip()]


def tracked_sources(repo_root: Path, section: configparser.SectionProxy) -> list[str]:
    """Every source file a note or a registry must cover, tracked or newly written.

    Untracked files are included deliberately: new code is untracked until it
    is committed, which is exactly when coverage matters most. Git variables a
    hook inherits (GIT_INDEX_FILE under `git commit -a`) are dropped, so the
    listing is always of repo_root's own repository.
    """
    directories = _listed(section, 'directories')
    suffixes = tuple(_listed(section, 'suffixes'))
    excluded = _listed(section, 'exclude')
    if not directories:
        return []
    listing = subprocess.run(['git', 'ls-files', '--cached', '--others', '--exclude-standard', *directories],
                             cwd=repo_root, capture_output=True, text=True,
                             env={k: v for k, v in os.environ.items() if not k.startswith('GIT_')})
    return sorted(path for path in listing.stdout.split()
                  if path.endswith(suffixes)
                  and not any(fnmatch.fnmatch(path, pattern) for pattern in excluded))


def registered(section: configparser.SectionProxy) -> set[str]:
    """Paths a registry already documents, which counts as coverage.

    Each entry is `module:attribute`; the attribute is any iterable of paths,
    or of objects with a `path` attribute. A registry that cannot be imported
    is reported rather than ignored, since silently counting nothing would
    turn coverage back off.
    """
    covered: set[str] = set()
    for entry in _listed(section, 'registries'):
        module_name, _, attribute = entry.partition(':')
        module = importlib.import_module(module_name)
        for item in getattr(module, attribute):
            covered.add(str(getattr(item, 'path', item)))
    return covered


def missing_covered(notes: list[Note], repo_root: Path) -> list[str]:
    """Files a note claims that are not there any more."""
    return [f'{n.path}: covers {c}, which does not exist'
            for n in notes for c in n.covers if not (repo_root / c).exists()]


def uncovered(notes: list[Note], repo_root: Path, section: configparser.SectionProxy) -> list[str]:
    """Source files neither a note nor a registry claims."""
    claimed = {c for n in notes for c in n.covers} | registered(section)
    return [s for s in tracked_sources(repo_root, section) if s not in claimed]


def duplicate_decisions(notes: list[Note]) -> list[str]:
    """Files claimed by more than one decision."""
    seen: dict[str, list[str]] = {}
    for note in (n for n in notes if n.kind == 'decision'):
        for covered in note.covers:
            seen.setdefault(covered, []).append(note.slug)
    return [f'{c} is decided by {" and ".join(slugs)}' for c, slugs in seen.items() if len(slugs) > 1]


def stale_evidence(notes: list[Note], repo_root: Path) -> list[str]:
    """Findings whose evidence command fails or no longer prints their claim."""
    problems = []
    for note in (n for n in notes if n.kind == 'finding' and n.evidence):
        result = subprocess.run(note.evidence, shell=True, cwd=repo_root, capture_output=True, text=True)
        if result.returncode != 0:
            problems.append(f'{note.slug}: evidence failed: {note.evidence}')
        elif note.claim and note.claim not in result.stdout:
            problems.append(f'{note.slug}: evidence no longer shows "{note.claim}"')
    return problems


def index(notes: list[Note], notes_root: Path) -> str:
    """The index table, built from what the notes declare.

    Each link is relative to the index, which sits in notes_root, so the table
    works wherever the repository is checked out.
    """
    rows = ''.join(f'| {n.kind} | [{n.title}]({n.path.relative_to(notes_root).as_posix()}) '
                   f'| {", ".join(n.covers) or "-"} |\n' for n in notes)
    return f'{INDEX_HEADER}\n| kind | note | covers |\n|---|---|---|\n{rows}'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--root', type=Path, default=Path('.'), help='the repository')
    parser.add_argument('--evidence', action='store_true', help="also re-run each finding's evidence")
    parser.add_argument('--skip-index', action='store_true', help='do not write notes/INDEX.md')
    args = parser.parse_args(argv)
    notes_root = args.root / 'notes'
    notes = load_all(notes_root)
    section = scope(notes_root)

    problems = missing_covered(notes, args.root)
    problems += [f'uncovered: {s}' for s in uncovered(notes, args.root, section)]
    problems += duplicate_decisions(notes)
    if args.evidence:
        problems += stale_evidence(notes, args.root)
    for problem in problems:
        print(f'  FAIL  {problem}')
    if not args.skip_index:
        (notes_root / 'INDEX.md').write_text(index(notes, notes_root), encoding='utf-8')
    print(f'  {len(notes)} note(s)' + ('' if args.skip_index else ', index regenerated'))
    if problems:
        print(f'\n  {len(problems)} problem(s)')
    return 1 if problems else 0


if __name__ == '__main__':
    sys.exit(main())
