#!/usr/bin/env bash
# repro_stack — one option for a reproducible project:
#   conda environment.yml pinned from imports, renv.lock + CmdStan, Dockerfile,
#   make targets (setup, pipeline, tests, gate, notes, site), pre-commit hooks,
#   and the working principles for contributors and Claude.
#
# New project:      init.sh (answer yes to "reproducible stack")
# Existing project: template/apply.sh --module repro_stack --output-dir <dir>

MODULE_NAME="repro_stack"
MODULE_DESCRIPTION="Reproducible stack: pinned conda + renv + CmdStan, Docker, make targets, hooks, working principles"
ACTIVATE_WHEN=("reproducible_stack=yes")
DEPENDS_ON=()
CONFLICTS_WITH=()
REQUIRED_VARS=("project_name")

REPRO_STACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

post_install() {
    _repro_makefile
    _repro_dockerfile
    _repro_precommit
    _repro_gate
    _repro_renv
    chmod +x .claude/hooks/*.sh 2>/dev/null || true
    if [[ "${REPRO_CLAUDE_PRIVATE:-}" == 1 ]]; then
        for entry in ".claude/" "CLAUDE.md"; do
            grep -qxF "$entry" .gitignore 2>/dev/null || echo "$entry" >> .gitignore
        done
    fi
    echo "  repro_stack: run 'make setup && make all'"
}

# Makefile: repro.mk owns the generic targets. Rules of the same name already in
# a generated Makefile are removed so each target has exactly one recipe.
_repro_makefile() {
    if [[ ! -f Makefile ]]; then
        printf '# Targets live in repro.mk; project values in project.mk.\ninclude repro.mk\n' > Makefile
        return
    fi
    grep -qE '^include repro\.mk' Makefile && return
    local targets
    targets=$(grep -oE '^[a-zA-Z_-]+:' repro.mk | tr -d ':' | sort -u | paste -sd'|')
    awk -v t="^(${targets}):" '
        $0 ~ t { skip = 1; next }
        skip && /^\t/ { next }
        { skip = 0; print }
    ' Makefile | grep -vE '^\.(PHONY|DEFAULT_GOAL)' > Makefile.tmp
    { cat Makefile.tmp; printf '\ninclude repro.mk\n'; } > Makefile
    rm -f Makefile.tmp
}

# Dockerfile: the stack image supersedes a language module's Dockerfile, but an
# existing project's own Dockerfile is kept when REPRO_KEEP_EXISTING=1.
_repro_dockerfile() {
    [[ -f Dockerfile.repro ]] || return
    if [[ -f Dockerfile && "${REPRO_KEEP_EXISTING:-}" == 1 ]]; then
        echo "  repro_stack: kept existing Dockerfile; stack version is Dockerfile.repro"
        return
    fi
    mv -f Dockerfile.repro Dockerfile
}

_repro_precommit() {
    local config=.pre-commit-config.yaml fragment="$REPRO_STACK_DIR/stack/pre-commit-hooks.yaml"
    grep -q 'id: repro-pipe-gate' "$config" 2>/dev/null && return
    if [[ ! -f "$config" ]]; then
        { echo "default_install_hook_types: [pre-commit, pre-push, commit-msg]"; echo "repos:"; cat "$fragment"; } > "$config"
        return
    fi
    if ! grep -q '^default_install_hook_types:' "$config"; then
        { echo "default_install_hook_types: [pre-commit, pre-push, commit-msg]"; cat "$config"; } > "$config.tmp"
        mv "$config.tmp" "$config"
    fi
    { echo ""; cat "$fragment"; } >> "$config"
}

# The pipe gate has one source: the style_pipelines module.
_repro_gate() {
    local scaffolded=correctness/checks/check_pipelines.py
    if [[ -f "$scaffolded" ]]; then
        sed -i "s|^PIPE_GATE .*|PIPE_GATE       = $scaffolded|" project.mk
    elif [[ ! -f tools/check_pipelines.py ]]; then
        mkdir -p tools
        cp "$REPRO_STACK_DIR/../style_pipelines/files/$scaffolded" tools/check_pipelines.py
    fi
}

# renv/activate.R is generated by the installed renv so its version matches.
_repro_renv() {
    [[ -f renv/activate.R ]] && return
    if command -v Rscript >/dev/null && Rscript --vanilla -e 'quit(status = !requireNamespace("renv", quietly = TRUE))' >/dev/null 2>&1; then
        local kept_profile
        kept_profile=$(<.Rprofile)
        Rscript --vanilla -e 'renv::scaffold(project = ".", repos = c(CRAN = "https://packagemanager.posit.co/cran/latest"))' >/dev/null
        printf '%s\n' "$kept_profile" > .Rprofile
        echo "  repro_stack: renv scaffolded; run 'make pin-renv' once R packages are installed"
    else
        echo "  repro_stack: R or renv not found; run renv::scaffold() later, then 'make pin-renv'"
    fi
}
