serve: ## Start full-stack server
	# TODO: Add full-stack server command
	@echo "Starting full-stack server..."

serve-backend: ## Start backend only
	# TODO: Add backend server command
	@echo "Starting backend..."

serve-frontend: ## Start frontend only
	# TODO: Add frontend server command
	@echo "Starting frontend..."
